NewsFeedReader.Web/Models/Feed/FeedItemModel.cs
using System;

namespace NewsFeedReader.Web.Models.Feed
{
    public class FeedItemModel
    {
        public string Name { get; set; }
        public string Url { get; set; }
        public string Text { get; set; }
        public DateTime PublicationDate { get; set; }  
        public FeedModel Feed { get;set; }
    }
}

NewsFeedReader.Web/Models/Feed/FeedModel.cs
using System.ComponentModel.DataAnnotations;

namespace NewsFeedReader.Web.Models.Feed
{
    public class FeedModel
    {
        public int Id { get; set; }

        [Required]
        [Url]
        [StringLength(1000)]
        public string Url { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }
    }
}

NewsFeedReader.Web/Controllers/FeedController.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using NewsFeedReader.BusinessLogic;
using NewsFeedReader.Domain;
using NewsFeedReader.Web.Models.Feed;

namespace NewsFeedReader.Web.Controllers
{
    [Authorize]
    public class FeedController : Controller
    {
        private readonly IFeedService feedService;

        public FeedController(IFeedService feedService)
        {
            this.feedService = feedService;
        }

        public ActionResult Index()
        {
            var allFeeds = Mapper.Map<List<FeedModel>>(feedService.GetAllFeeds(User.Identity.GetUserId()));
            return View(allFeeds);
        }

        public ActionResult View(int feedId)
        {
            try
            {
                return View(Mapper.Map<List<FeedItemModel>>(feedService.FetchFeedItems(User.Identity.GetUserId(), feedId)));
            }
            catch (FeedNotFoundException ex)
            {
                throw new HttpException(404, "Not found", ex);
            }
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(FeedModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var feed = Mapper.Map<Feed>(model);
            feed.ApplicationUserId = User.Identity.GetUserId();
            feedService.AddFeed(feed);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int feedId)
        {
            try
            {
                var feed = feedService.GetFeed(User.Identity.GetUserId(), feedId);
                return View(Mapper.Map<FeedModel>(feed));
            }
            catch (FeedNotFoundException ex)
            {
                throw new HttpException(404, "Not found", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(FeedModel feedModel)
        {
            try
            {
                var feed = feedService.GetFeed(User.Identity.GetUserId(), feedModel.Id);
                feedService.DeleteFeed(feed);
                return RedirectToAction("Index");
            }
            catch (FeedNotFoundException ex)
            {
                throw new HttpException(404, "Not found", ex);
            }
        }

        public ActionResult Search(string search)
        {
            var feedItems = feedService.FetchFeedItems(User.Identity.GetUserId(), search);
            return View(Mapper.Map<List<FeedItemModel>>(feedItems));
        }
    }
}

NewsFeedReader.Web/Views/Feed/Add.cshtml
@model NewsFeedReader.Web.Models.Feed.FeedModel

@{
    ViewBag.Title = "Add new feed";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Add", "Feed", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Url, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Url, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewsFeedReader.Web/Views/Feed/Delete.cshtml
@model NewsFeedReader.Web.Models.Feed.FeedModel

@{
    ViewBag.Title = "Unsubscribe feed";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Delete", "Feed", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new {@class = "text-danger"})

    @Html.HiddenFor(m => m.Id)

<p>Are you sure that you want to unsubscribe from the feed @Html.ActionLink(Model.Name, "View", "Feed", new {feedId = Model.Id}, null) ?</p>

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" class="btn btn-danger" value="Unsubscribe"/>
            @Html.ActionLink("Cancel", "Index", null, new {@class = "btn btn-default"})
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewsFeedReader.Web/Views/Feed/Index.cshtml
@model List<NewsFeedReader.Web.Models.Feed.FeedModel>

@{
    ViewBag.Title = "Feed Subscriptions";
}

<h2>@ViewBag.Title.</h2>

<p>
    <a href="@Url.Action("Add", "Feed")" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add New Feed
    </a>
</p>

@if (Model.Count == 0)
{
    <p>You don't have any subscriptions. Please, add one.</p>
}
else
{
    <table class="table table-striped">
        @foreach (var feed in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(feed.Name, "View", new {feedId = feed.Id})
                </td>
                <td>
                    @feed.Url
                </td>
                <td>
                    @Html.ActionLink("Unsubscribe", "Delete", new { feedId = feed.Id })
                </td>
            </tr>
        }
    </table>
}

NewsFeedReader.Web/Views/Feed/Search.cshtml
@model List<NewsFeedReader.Web.Models.Feed.FeedItemModel>

@{
    ViewBag.Title = "Found Feed Items";
}

<h2>
    <span>@ViewBag.Title</span>
    <a href="@Url.Action("Index", "Home")" class="btn btn-primary">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Go To The Main Screen
    </a>
</h2>

@if (Model.Count == 0)
{
    <p>
        Looks like this search didn't return any results
    </p>
}
else
{
    @Html.Partial("_FeedItems")
}

NewsFeedReader.Web/Views/Feed/View.cshtml
@model List<NewsFeedReader.Web.Models.Feed.FeedItemModel>

@{
    ViewBag.Title = "Feed Items";
}

<h2>
    <span>@ViewBag.Title @(Model.Count > 0 ? $"on {Model[0].Feed.Name}" : "")</span>
    <a href="@Url.Action("Index", "Feed")" class="btn btn-primary">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Go To All Feeds
    </a>
</h2>

@if (Model.Count == 0)
{
    <p>
        Looks like this feed doesn't have any feed items.
    </p>
}
else
{
    @Html.Partial("_FeedItems")
}